FROM dmiseev/php-fpm7.3

RUN composer self-update
WORKDIR /
# RUN chown -R $USER:$USER /var/www/html/magento2/ 
# RUN chmod -R 777 /var/www/html/magento2/
# RUN sh -c "echo '127.0.0.1 vinhvuvuot-dev.com' >> /etc/hosts"
